spring:
  profiles:
    active:
      - test
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:libraryDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle
    driverClassName: org.h2.Driver
    username: ENC(3EPPMlwajdDJ77vU7T08ojeyy00rCYT6dvZv8ZG6I+exXGCFhFtlJ60qW8gfUWjg)
    password: ENC(aLtQiTPPSl9o0r2vE1CRCZnuK8cns73wv12vRQCRvAIeOUuzxpZSi03XTPgemmhA)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

server:
  port: 5055

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:libraryDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle
    driverClassName: org.h2.Driver
    username: user1
    password: pss1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

server:
  port: 5055
